name: Terraform Deployment

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "action is running"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - uses: actions/checkout@v2
      - name: Goodbye World
        run: echo "action is done"
        shell: bash